---
- name: Set up and launch frontend stack remotely
  hosts: frontend
  become: true

  vars:
    deploy_dir: /opt/app
# 
  tasks:
    - name: Ensure deployment directory exists
      ansible.builtin.file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Transfer Docker Compose configuration
      ansible.builtin.copy:
        src: compose.yml
        dest: "{{ deploy_dir }}/compose.yml"
        mode: '0644'

    - name: Upload Nginx configuration
      ansible.builtin.copy:
        src: default.conf
        dest: "{{ deploy_dir }}/default.conf"
        mode: '0644'

    - name: Pull updated Docker images
      ansible.builtin.shell: docker-compose -f compose.yml pull
      args:
        chdir: "{{ deploy_dir }}"

    # - name: Build and run containers in detached mode
    #   ansible.builtin.shell: docker-compose -f compose.yml up --build -d
    #   args:
    #     chdir: "{{ deploy_dir }}"