- name: Setup MongoDB using Docker Compose
  hosts: all
  become: yes

  vars:
    docker_compose_version: "v2.27.0"

  tasks:
    - name: Install required system packages (Ubuntu/Debian)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Docker (Ubuntu)
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io]
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Docker (Amazon Linux)
      yum:
        name: docker
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create app directory
      file:
        path: /opt/mongodb
        state: directory

    - name: Copy compose.yaml to target server
      copy:
        src: ./compose.yaml
        dest: /opt/mongodb/compose.yaml

    - name: Run docker-compose using compose.yaml
      command: docker-compose -f compose.yaml up -d
      args:
        chdir: /opt/mongodb
