name: Deploy Backend Only

on:
  push:
    paths:
      - 'backend/**'
      - 'backend-instance-EC2/**'
      - '.github/workflows/deploy-backend.yml'
      - 'compose.yml'
      - '.env'
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend:latest

      - name: Deploy Backend via Ansible
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd mern-gallery-sample-app
            git fetch
            git pull
            cd ../ansible
            ansible-playbook -i inventory.ini ../mern-gallery-sample-app/backend-instance-EC2/playbook.yaml --limit backend
