name: Deploy Backend Only

on:
  push:
    paths:
      - 'backend/**'
      - 'backend-instance-EC2/**'
      - '.github/workflows/deploy-backend.yml'
      - 'compose.yml'
      - 'instance-file.yaml'
      - '.env'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to Bastion and Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BASTION_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd mern-gallery-sample-app
            git fetch && git pull
            cd ansible
            ansible-playbook -i inventory.ini ../mern-gallery-sample-app/backend-instance-EC2/playbook.yaml --limit backend
